#!/usr/bin/env node

const chalk = require('chalk');
const quotes = require('./quotes.json');

const randomElementInArray = array =>
  array[Math.floor(Math.random()*array.length)];

const quote = randomElementInArray(quotes);

const log = console.log;

log();
log(chalk.bold(`\t${quote.text}`));
log(chalk.dim.italic(`\t___${quote.from}`));
log();
